version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
  web:
    image: node:7.9.0
    command: npm start --prefix myapp/client
    volumes:
      - .:/myapp
    ports: 
      - "3000:3000"
    depends_on:
      - api
volumes:
  postgres-data: